<?php

/**
 * @file
 * Contains dbee_user_email_fix.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dbee_user_email_fix_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dbee_user_email_fix module.
    case 'help.page.dbee_user_email_fix':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Ensures email addresses are decrypted in system user emails.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail_alter().
 */
function dbee_user_email_fix_mail_alter(&$message) {
  if ($message['module'] == 'user' && ($message['key'] == 'status_blocked' || $message['key'] == 'status_activated')) {
    $message['to'] = dbee_decrypt($message['params']['account']->getEmail());
  }
}
